spring:
  datasource:
    url: jdbc:mysql://172.18.51.88:3306/capsule
    username: root
    password: runa
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    
  main:
    banner-mode: "off"